---
title: "Ruibo Sun's Website"
---

Enthusiastic economics and statistics student at the University of Toronto with strong academic background and understanding of analysis.

# Skills
- Proficient with Microsoft Office Suite (PowerPoint, Word, Excel) and G Suite Programs (Google Docs, Google Sheets, Google Slides)
- Basic Knowledge of R, Python, SQL
- Self-motivated and excellent communication skills with diverse stakeholders

# Education
- *Financial Economics Specialist and Specialist in Statistical Science (Methods and Practice)*
University of Toronto - St. George Campus
- **Art and Science Internship Program (Co-op Program)**
-	**Course Work**: Intermediate level of Microeconomics and Macroeconomics, Probability and Statistics, Theory of Statistical Practice, Observation data and Sampling, Linear Regression and Statistical Methods for Machine Learning
-	**GPA**: 3.87/4.0
-	**Awards**: Dean's List for 2021 Summer and 2022 Winter, Jackman Scholars-in-Residence Scholarship 2022 and Mary Keenan Award 2022

# Experience
**Statistical Science Department, University of Toronto -- Statistical Consultant**							                   
- Searched ahead on speakers’ research interests and prepared for statistical insights/suggestions that are closely related to their specific research topics.
- Communicated effectively with speakers from diverse fields/backgrounds in verbal and non-verbal communication.

**Economics Department, University of Toronto -- Research Assistant**
- Used Excel to perform regular data entry tasks and data manipulation independently on annual reports from 1978 to 2020 for the US Railroads and merged data into one file.
- Used R to clean and visualize the critical data/variables across time for further analysis.

